#include "avl.h"
static int max(int a,int b){return a>b?a:b;}
static int height(struct avl_node *n){return n?n->height:0;}
static struct avl_node *node_create(const char *key,void *value){ struct avl_node *n=calloc(1,sizeof(*n)); if(!n){perror("calloc");exit(1);} n->key=xstrdup(key); n->value=value; n->height=1; return n; }
static struct avl_node *right_rotate(struct avl_node *y){ struct avl_node *x=y->left; struct avl_node *T2=x->right; x->right=y; y->left=T2; y->height=max(height(y->left),height(y->right))+1; x->height=max(height(x->left),height(x->right))+1; return x; }
static struct avl_node *left_rotate(struct avl_node *x){ struct avl_node *y=x->right; struct avl_node *T2=y->left; y->left=x; x->right=T2; x->height=max(height(x->left),height(x->right))+1; y->height=max(height(y->left),height(y->right))+1; return y; }
static int get_balance(struct avl_node *n){return n?height(n->left)-height(n->right):0;}
static struct avl_node *avl_insert_node(struct avl_node *node,const char *key,void *value,void **old){ if(!node) return node_create(key,value); int cmp=strcmp(key,node->key); if(cmp==0){ if(old)*old=node->value; node->value=value; return node;} if(cmp<0) node->left=avl_insert_node(node->left,key,value,old); else node->right=avl_insert_node(node->right,key,value,old); node->height=1+max(height(node->left),height(node->right)); int balance=get_balance(node); if(balance>1&&strcmp(key,node->left->key)<0) return right_rotate(node); if(balance<-1&&strcmp(key,node->right->key)>0) return left_rotate(node); if(balance>1&&strcmp(key,node->left->key)>0){ node->left=left_rotate(node->left); return right_rotate(node);} if(balance<-1&&strcmp(key,node->right->key)<0){ node->right=right_rotate(node->right); return left_rotate(node);} return node; }
struct avl_tree *avl_create(void){ struct avl_tree *t=calloc(1,sizeof(*t)); if(!t){perror("calloc");exit(1);} return t;}
void *avl_insert(struct avl_tree *t,const char *key,void *value){ void *old=NULL; t->root=avl_insert_node(t->root,key,value,&old); return old;}
static void avl_free_node(struct avl_node *n,void (*free_value)(void*)){ if(!n)return; avl_free_node(n->left,free_value); avl_free_node(n->right,free_value); if(free_value && n->value) free_value(n->value); free(n->key); free(n);}
void avl_free(struct avl_tree *t,void (*free_value)(void*)){ if(!t)return; avl_free_node(t->root,free_value); free(t);}
void *avl_get(struct avl_tree *t,const char *key){ struct avl_node *cur=t->root; while(cur){ int cmp=strcmp(key,cur->key); if(cmp==0) return cur->value; cur=(cmp<0)?cur->left:cur->right;} return NULL; }